#! /bin/sh

# This entire thing seems silly and wrong and should probably just go away completely.

# <<<<<<< HEAD
#lein localrepo install target/penumbra-0.6.5-SNAPSHOT.jar /jimrthy/penumbra 0.6.5-SNAPSHOT
lein install
# =======
lein uberjar
lein localrepo install target/penumbra-0.6.6-SNAPSHOT.jar /jimrthy/penumbra 0.6.6-SNAPSHOT
# >>>>>>> d5be6fa1a8876ab0c11ab22e364683fbe5487b84

echo "lein install seems to be plenty."
